version: "3.1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: base_db
    ports:
      - "5432:5432"
    
  volumes:
      - /your/mount_pt:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dbadmin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ****
    ports:
      - "5050:80"
